<footer class="w3-container footer" style="background-color:#2E4A4F; color:#E7FFF9;">
    <div class="w3-row" style="display: flex;">
    
        <div class="w3-half w3-center w3-padding">
            <h3>Contacteer ons</h3>
            <p>Email: info@hypermobiliteitcenter.be</p>
            <p>Telefoon: +32 473 227 010</p>
            <p>Adres: Sportstraat 10, 9000 Gent, België</p>
        </div>

        <div class="w3-half w3-center w3-padding" style="display: flex; justify-content: center; align-items: center;">
            <img src="hypermobility_logo.png" alt="Hypermobility Central Logo" style="width: 125px; height:125px;">
        </div>
    </div>
</footer>
